# Generated by Django 5.0.1 on 2024-01-14 09:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='url_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='category url title'),
        ),
        migrations.CreateModel(
            name='ArticleSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='subcategory title')),
                ('url_title', models.CharField(max_length=300, verbose_name='subcategory url title')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='short description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('selected_categories', models.ManyToManyField(blank=True, to='article.articlecategory', verbose_name="subcategory's categories")),
            ],
            options={
                'verbose_name': 'article subcategory',
                'verbose_name_plural': 'article subcategories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='article title')),
                ('url_title', models.CharField(db_index=True, max_length=350, verbose_name='article url title')),
                ('image', models.ImageField(blank=True, upload_to='images/article', verbose_name='article image')),
                ('short_description', models.TextField(blank=True, verbose_name='short description')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='article text')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('selected_categories', models.ManyToManyField(blank=True, to='article.articlecategory', verbose_name="article's categories")),
                ('selected_subcategories', models.ManyToManyField(blank=True, to='article.articlesubcategory', verbose_name="article's subcategories")),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
