# Generated by Django 5.0.1 on 2024-01-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlecategory_url_title_articlesubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='articlesubcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='articlesubcategory',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='priority'),
        ),
    ]
