# Generated by Django 5.0.1 on 2024-01-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlesubcategory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesubcategory',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='author name'),
        ),
    ]
