# Generated by Django 5.0.1 on 2024-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_with_code',
            field=models.TextField(blank=True, verbose_name='article text with code'),
        ),
    ]
