# Generated by Django 5.0.1 on 2024-01-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_text_with_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='short description'),
        ),
    ]
